### ISSUE TITLE
Publish new release

### ISSUE THREAD

**Issue by fredyshox** [sindresorhus/Defaults#41]
Current latest release is outdated. Could you draft a new release?
I suggest publishing everything up to [`3275717`](https://github.com/sindresorhus/Defaults/commit/3275717838bdaab27df2357b071bff4d2b44adfd), and then current master in separate releases (as there are some incompatible changes).

**Comment by fredyshox** [comment]
Ok, I missed the note about the [bug](https://github.com/feedback-assistant/reports/issues/44) in README. But still this occurs only while using SwiftPM, for Carthage/Pods `-weak_framework` can be used.

**Comment by sindresorhus** [comment]
I was hoping to confirm whether that issue mentioned in the readme was fixed in Xcode 11.4 or not before publishing.

If you or anyone you know are on macOS 10.14, you could try to launch 
[Dato-xcode-bug.zip](https://github.com/sindresorhus/Defaults/files/4480769/Dato-xcode-bug.zip) and if it launches successfully, it means the bug was fixed.

**Comment by fredyshox** [comment]
I've tried on 10.14.6, and it doesn't work (status -1).

**Comment by sindresorhus** [comment]
> I suggest publishing everything up to 3275717, 

Because of that Xcode bug, the Combine addition is also a breaking change, so I'm just gonna release them all as a single major release.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/Defaults/releases/tag/v4.0.0
